import { Command } from 'commander';
import pc from 'picocolors';
import fs from 'node:fs';
import path from 'node:path';
import { logger } from '../utils/logger.js';
import { createSpinner } from '../utils/spinner.js';

export function registerDocsCommand(program: Command): void {
  program
    .command('docs')
    .description('Generate documentation for the MCP server')
    .option('-o, --outDir <outDir>', 'Output directory', 'docs')
    .option('-v, --verbose', 'Verbose output')
    .action(async (options) => {
      await runDocs(options);
    });
}

interface DocsOptions {
  outDir: string;
  verbose: boolean;
}

async function runDocs(options: DocsOptions): Promise<void> {
  const spinner = createSpinner('Generating documentation...').start();

  try {
    const projectDir = process.cwd();
    const outDir = path.resolve(projectDir, options.outDir);

    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }

    const srcDir = path.join(projectDir, 'src');
    if (!fs.existsSync(srcDir)) {
      spinner.fail('Source directory not found');
      logger.error('Make sure you are in the project root directory.');
      process.exit(1);
    }

    const toolsDir = path.join(srcDir, 'tools');
    const tools: string[] = [];

    if (fs.existsSync(toolsDir)) {
      const files = fs.readdirSync(toolsDir).filter((f) => f.endsWith('.ts'));
      files.forEach((file) => {
        const content = fs.readFileSync(path.join(toolsDir, file), 'utf-8');
        const nameMatch = content.match(/name:\s*['"]([^'"]+)['"]/);
        const descMatch = content.match(/description:\s*['"]([^'"]+)['"]/);
        if (nameMatch?.[1]) {
          tools.push(nameMatch[1]);
        }
      });
    }

    const readmePath = path.join(projectDir, 'README.md');
    const readme = fs.existsSync(readmePath) ? fs.readFileSync(readmePath, 'utf-8') : '';

    const docsContent = `# API Documentation

Generated by mcpkit

## Tools

${tools.length > 0
  ? tools.map((t) => `- ${t}`).join('\n')
  : 'No tools found. Register tools in your server.'}

## Quick Start

\`\`\`bash
# Install dependencies
bun install

# Start development server
bun run dev

# Build for production
bun run build
\`\`\`

## Configuration

This MCP server uses stdio transport for communication.

### VS Code

Add to \`.vscode/mcp.json\`:

\`\`\`json
{
  "servers": {
    "mcp-server": {
      "type": "stdio",
      "command": "node",
      "args": ["./dist/index.js"]
    }
  }
}
\`\`\`
`;

    fs.writeFileSync(path.join(outDir, 'api.md'), docsContent);

    spinner.succeed('Documentation generated!');
    logger.break();
    logger.success(`Docs written to ${pc.cyan(options.outDir + '/')}`);
  } catch (err) {
    spinner.fail('Documentation generation failed');
    logger.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
}
