// @ts-nocheck
import * as __fd_glob_57 from "../content/docs/templates/index.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/templates/http.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/templates/full.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/templates/choosing-a-template.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/templates/basic.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/templates/auth.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/help/troubleshooting.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/help/index.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/help/faq.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/help/changelog.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/guides/validation.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/guides/testing-mcp-servers.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/guides/shell-completions.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/guides/publishing.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/guides/mcp-inspector.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/guides/index.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/guides/environment-configuration.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/guides/diagnostics.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/guides/development-workflow.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/guides/building-for-production.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/concepts/transports.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/concepts/tools.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/concepts/resources.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/concepts/prompts.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/concepts/mcp-servers.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/concepts/index.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/examples/index.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/examples/http-server.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/examples/basic-stdio-server.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/examples/authenticated-http-server.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/getting-started/understand-generated-project.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/getting-started/test-it.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/getting-started/run-it.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/getting-started/first-server.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/cli/validate.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/cli/test.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/cli/ship.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/cli/init.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/cli/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/cli/doctor.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/cli/docs.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/cli/dev.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/cli/completions.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/cli/check-env.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/cli/build.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/why-mcpkit.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/quick-start.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/installation.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/templates/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/help/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/examples/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/concepts/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/cli/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "cli/meta.json": __fd_glob_1, "concepts/meta.json": __fd_glob_2, "examples/meta.json": __fd_glob_3, "guides/meta.json": __fd_glob_4, "getting-started/meta.json": __fd_glob_5, "help/meta.json": __fd_glob_6, "templates/meta.json": __fd_glob_7, }, {"index.mdx": __fd_glob_8, "installation.mdx": __fd_glob_9, "quick-start.mdx": __fd_glob_10, "why-mcpkit.mdx": __fd_glob_11, "cli/build.mdx": __fd_glob_12, "cli/check-env.mdx": __fd_glob_13, "cli/completions.mdx": __fd_glob_14, "cli/dev.mdx": __fd_glob_15, "cli/docs.mdx": __fd_glob_16, "cli/doctor.mdx": __fd_glob_17, "cli/index.mdx": __fd_glob_18, "cli/init.mdx": __fd_glob_19, "cli/ship.mdx": __fd_glob_20, "cli/test.mdx": __fd_glob_21, "cli/validate.mdx": __fd_glob_22, "getting-started/first-server.mdx": __fd_glob_23, "getting-started/index.mdx": __fd_glob_24, "getting-started/run-it.mdx": __fd_glob_25, "getting-started/test-it.mdx": __fd_glob_26, "getting-started/understand-generated-project.mdx": __fd_glob_27, "examples/authenticated-http-server.mdx": __fd_glob_28, "examples/basic-stdio-server.mdx": __fd_glob_29, "examples/http-server.mdx": __fd_glob_30, "examples/index.mdx": __fd_glob_31, "concepts/index.mdx": __fd_glob_32, "concepts/mcp-servers.mdx": __fd_glob_33, "concepts/prompts.mdx": __fd_glob_34, "concepts/resources.mdx": __fd_glob_35, "concepts/tools.mdx": __fd_glob_36, "concepts/transports.mdx": __fd_glob_37, "guides/building-for-production.mdx": __fd_glob_38, "guides/development-workflow.mdx": __fd_glob_39, "guides/diagnostics.mdx": __fd_glob_40, "guides/environment-configuration.mdx": __fd_glob_41, "guides/index.mdx": __fd_glob_42, "guides/mcp-inspector.mdx": __fd_glob_43, "guides/publishing.mdx": __fd_glob_44, "guides/shell-completions.mdx": __fd_glob_45, "guides/testing-mcp-servers.mdx": __fd_glob_46, "guides/validation.mdx": __fd_glob_47, "help/changelog.mdx": __fd_glob_48, "help/faq.mdx": __fd_glob_49, "help/index.mdx": __fd_glob_50, "help/troubleshooting.mdx": __fd_glob_51, "templates/auth.mdx": __fd_glob_52, "templates/basic.mdx": __fd_glob_53, "templates/choosing-a-template.mdx": __fd_glob_54, "templates/full.mdx": __fd_glob_55, "templates/http.mdx": __fd_glob_56, "templates/index.mdx": __fd_glob_57, });